#!/bin/bash

svc_tcpdump -W 5 -C 200 -i bond2 -F "/home/service/user/tcpdumpfilter.txt" &
P=$!

while kill -0 $P 2>/dev/null; do
    if grep -q "The DNS client is unable to connect to name server" /EMC/C4Core/log/c4_safe_ktrace.log; then
        kill -- -$P
        break
    fi
    sleep 5
done
